import Link from 'next/link'
import { ArrowRight, Bot, Check, Gauge, MapPin, ShieldCheck, Sparkles, Wifi } from 'lucide-react'
import { SiteShell } from '@/components/site-shell'

const reasons = [{ icon: Gauge, title: 'Gyors indulás', text: 'A botod rövid időn belül használatra kész.' }, { icon: ShieldCheck, title: 'DDoS védelem', text: 'Alap biztonság, hogy nyugodtan futhasson.' }, { icon: MapPin, title: 'Frankfurt, Németország', text: 'Közeli helyszín, alacsonyabb késleltetés.' }]
export default function Page() { return <SiteShell><main>
  <section className="relative overflow-hidden"><div className="absolute -right-32 -top-28 size-[28rem] rounded-full bg-[#c7585b]/10 blur-3xl" /><div className="mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24">
    <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#e1b4b5] bg-[#fff8f7] px-4 py-2 text-xs font-bold text-[#a23b3e]"><Sparkles size={14} /> Egyszerű hosting, korrekt áron</div><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-.06em] text-[#2a292a] sm:text-7xl">A botodnak <span className="text-[#ef343b]">otthona</span> van.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/60">Megbízható Discord bot hosting Frankfurtból. Felesleges sallangok nélkül, baráti áron, folyamatos üzemmel.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/csomagok" className="inline-flex items-center gap-2 rounded-xl bg-[#b33a3d] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#b33a3d]/20 transition hover:bg-[#942f33]">Csomag megtekintése <ArrowRight size={17} /></Link><a href="#miert" className="rounded-xl border border-white/15 px-6 py-3.5 font-bold text-white/75 transition hover:bg-white/5">Miért dewyhosting?</a><a href="https://panel.dewyofficial.hu" target="_blank" rel="noreferrer" className="rounded-xl border border-[#d71920]/60 px-6 py-3.5 font-bold text-[#ef343b] transition hover:bg-[#d71920]/10">Panel megnyitása</a></div></div>
    <div className="relative rounded-[2rem] border border-[#ded8d6] bg-[#111111] p-5 shadow-[0_24px_70px_-35px_rgba(80,36,38,.35)]"><div className="rounded-[1.4rem] bg-[#2e2d2e] p-7 text-white"><div className="flex items-center justify-between"><div><p className="text-sm text-white/60">dewyhosting</p><h2 className="mt-1 text-2xl font-bold">Szerverünk készen áll.</h2></div><div className="flex size-11 items-center justify-center rounded-xl bg-[#b33a3d]"><Bot /></div></div><div className="mt-10 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><Wifi className="mb-3 text-[#e77a7d]" size={19} /><p className="text-xl font-black">1 Gbps</p><p className="text-xs text-white/50">hálózat</p></div><div className="rounded-xl bg-white/10 p-4"><p className="mb-3 text-[#e77a7d]">RAM</p><p className="text-xl font-black">16 GB</p><p className="text-xs text-white/50">memória</p></div></div><div className="mt-3 rounded-xl border border-white/10 p-4 text-sm text-white/70"><span className="mr-2 inline-block size-2 rounded-full bg-[#62c477]" /> Online · Frankfurt, DE</div></div></div>
  </div></section>
  <section id="miert" className="border-y border-[#dedbd8] bg-[#111111]"><div className="mx-auto max-w-6xl px-5 py-16 lg:px-8"><div className="max-w-xl"><p className="eyebrow">Miért minket?</p><h2 className="section-title">Ami tényleg számít.</h2><p className="mt-4 text-white/60">Egy kis projekt, nagy odafigyeléssel. Nálunk nem veszel meg egy túlbonyolított csomagot, csak azt kapod, amire a botodnak szüksége van.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{reasons.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-[#ded8d6] bg-[#f7f6f4] p-6"><Icon className="text-[#ef343b]" size={22} /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#777274]">{text}</p></div>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-16 lg:px-8"><div className="flex flex-col items-start justify-between gap-6 rounded-3xl bg-[#b33a3d] p-8 text-white sm:flex-row sm:items-center sm:p-12"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-white/60">ELSO10</p><h2 className="mt-2 text-3xl font-black tracking-tight">10% kedvezmény az első rendelésedre.</h2><p className="mt-2 text-white/75">Használd a kódot a rendelésnél.</p></div><Link href="/csomagok" className="shrink-0 rounded-xl bg-white px-5 py-3 font-bold text-[#a23b3e] transition hover:bg-[#fff2f1]">Kipróbálom <ArrowRight className="ml-2 inline" size={16} /></Link></div><div className="mt-12 text-center"><p className="mx-auto max-w-2xl text-sm leading-7 text-[#858082]"><Check className="mr-2 inline text-[#ef343b]" size={16} /> A dewyhosting egy hobbyprojekt. Ettől függetlenül mindent megteszünk, hogy a szolgáltatásod stabilan és megbízhatóan fusson.</p></div></section>
</main></SiteShell> }
